[mypy]
python_version = 3.6
files = pypi/**/*.py
disallow_untyped_defs = true

[mypy-flask_migrate]
ignore_missing_imports = True

[mypy-flask_sqlalchemy]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True
