[flake8]
exclude =
    build
    dist
    .venv
    .tox
    migrations
ignore = E203, W503
max-line-length = 100

[pytest]
addopts = --junitxml=junit/test-results.xml --cov=pypi --cov-report=xml

[pydocstyle]
ignore = D105,D107,D203,D204,D213,D215,D400,D401,D404,D406,D407,D408,D409